name: AWS OIDC Auth
description: Authenticate to AWS using OIDC
inputs:
  AWS_ACCOUNT:
    description: Account number to authenticate
    required: true
  AWS_ROLE:
    description: AWS role used to authenticate
    required: false
    default: oidc-github-actions

runs:
  using: 'composite'
  steps:    
    - uses: aws-actions/configure-aws-credentials@v4.0.3
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT }}:role/${{ inputs.AWS_ROLE }}