name: Reusable workflow for SYNC S3
on:
  workflow_call:
    inputs:
      AWS_ROLE:
        description: AWS role used to authenticate
        required: false
        default: oidc-github-actions
        type: string
      WORK_DIR:
        description: Directory where are
        required: false
        default: "/src/html"
        type: string
      S3_BUCKET:
        description: Bucket name
        required: true
        type: string
      CLOUD_FRONT_DISTRIBUTION_ID:
        required: true
        type: string
      ENVIRONMENT:
        description: Github Environment
        required: false
        default: auto
        type: string


    secrets:
      GH_TOKEN:
        description: GH TOKEN for accessing to privates repos
        required: false
      AWS_ACCOUNT:
        description: Account number to authenticate
        required: true


jobs:
  aws_sync_s3:
    runs-on: ubuntu-latest
    name: Sync AWS S3
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository.full_name}}
          token: ${{ secrets.GH_TOKEN }} 
        if: github.repository_visibility == private
      - name: Aws OIDC Auth
        uses: fabrinator/actions/.github/actions/aws-oidc-auth@feature/oidc-auth
        with:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}    
      - name: Sync S3
        run: aws s3 sync ./  s3://${{ inputs.S3_BUCKET }}
        working-directory: ${{ inputs.WORK_DIR}}
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ inputs.CLOUD_FRONT_DISTRIBUTION_ID}} --paths "/*"                