name: Reusable workflow for AWS SAM
on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: true
        type: string
      PROJECT_FOLDER:
        required: true
        type: string



jobs:
  requirements:
    runs-on: ubuntu-latest
    name: Requirements
    environment:  auto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
          cache: 'pip'
      - run: pip install -r ${{ inputs.PROJECT_FOLDER }}/tests/requirements.txt
      - name: SAM Validate
        run: |
          sam validate
        working-directory: ${{ inputs.PROJECT_FOLDER }}