name: Reusable workflow for SYNC S3
on:
  workflow_call:
    inputs:
      AWS_ACCOUNT:
        description: Account number to authenticate
        required: true
        type: string
      AWS_ROLE:
        description: AWS role used to authenticate
        required: false
        default: oidc-github-actions
        type: string


jobs:
  aws_sync_s3:
    runs-on: ubuntu-latest
    name: Requirements
    steps:
      - name: Aws OIDC Auth
        uses: fabrinator/actions/.github/actions/aws-oidc-auth@feature/oidc-auth
        with:
          AWS_ACCOUNT: ${{ inputs.AWS_ACCOUNT }}    
      - name: Sync S3
        run: aws s3 sync ./  s3://dev.fabririvas.com   
        working-directory: "src/html"
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E3D7115DJ5R44C --paths "/*"                