name: Reusable workflow for Deploy CDK
on:
  workflow_call:
    inputs:
      AWS_ROLE:
        description: AWS role used to authenticate
        required: false
        default: oidc-github-actions
        type: string
      WORK_DIR:
        description: Directory where are
        required: false
        default: "/src/html"
        type: string
      ENVIRONMENT:
        description: Github Environment
        required: false
        default: auto
        type: string
      NODE_VERSION:
        description: Node version
        required: false
        default: 22
        type: string


    secrets:
      GH_TOKEN:
        description: GH TOKEN for accessing to privates repos
        required: false
      AWS_ACCOUNT:
        description: Account number to authenticate
        required: true


jobs:
  aws_sync_s3:
    runs-on: ubuntu-latest
    name: Sync AWS S3
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout 
        uses: fabrinator/actions/.github/actions/github-checkout@feature/oidc-auth
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 

      - name: Aws OIDC Auth
        uses: fabrinator/actions/.github/actions/aws-oidc-auth@feature/oidc-auth
        with:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}             

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}        

      - name: Install aws cdk
        run: npm install -g aws-cdk@2.175.1          

      - name: Node dependencies
        run: npm install
        working-directory: ${{ inputs.WORK_DIR}}   

      - name: aws cdk diff
        run: cdk diff
        working-directory: ${{ inputs.WORK_DIR}}    

      - name: aws cdk Deploy
        run: cdk deploy --require-approval never
        working-directory: ${{ inputs.WORK_DIR}}                      